# Generated by Django 5.0.6 on 2024-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Mother_Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('College_Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=20)),
                ('Phone_Number', models.IntegerField()),
                ('Upload_images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
