# Generated by Django 5.0.6 on 2024-08-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
